version: 0.2

phases:
  build:
    commands:
      - npm ci
      - npm run build
  post_build:
    commands:
      - echo Missing AWS S3 sync

artifacts:
  name: build
  type: zip
  base-directory: dist/tokenlab-v2
  files:
    - '*'
