version: 0.2

phases:
  pre_build:
    commands:
      - sed "s|ENDPOINT|$ENDPOINT|g" -i src/environments/environment.prod.ts
  build:
    commands:
      - npm ci
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/tokenlab-v2 s3://${DEPLOY_BUCKET} --delete
