version: 0.2
# [Container] 2021/07/27 18:58:34 Found possible syntax errors in buildspec:
  #In the section artifacts
#    The following keys cannot be identified:
#        type
phases:
  build:
    commands:
      - npm ci
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/tokenlab-v2 s3://${DEPLOY_BUCKET} --delete
